if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Use as ./linecount.bash <line-count-txt-file> <implementation folder>"
  echo "Where <line-count-txt-file> is generated by atoms Line Count package."
else
  cat $1 | grep "$2/src$\|$2/es6-test$"
  cat $1 | grep "$2src$\|$2es6-test$"
fi
